// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Master.proto

package org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated;

public final class Master {
  private Master() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KeysOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Keys)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string key = 1;</code>
     */
    java.util.List<java.lang.String>
        getKeyList();
    /**
     * <code>repeated string key = 1;</code>
     */
    int getKeyCount();
    /**
     * <code>repeated string key = 1;</code>
     */
    java.lang.String getKey(int index);
    /**
     * <code>repeated string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes(int index);
  }
  /**
   * Protobuf type {@code Keys}
   */
  public  static final class Keys extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Keys)
      KeysOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Keys.newBuilder() to construct.
    private Keys(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Keys() {
      key_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Keys(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                key_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              key_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          key_ = key_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.internal_static_Keys_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.internal_static_Keys_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys.class, org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList key_;
    /**
     * <code>repeated string key = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getKeyList() {
      return key_;
    }
    /**
     * <code>repeated string key = 1;</code>
     */
    public int getKeyCount() {
      return key_.size();
    }
    /**
     * <code>repeated string key = 1;</code>
     */
    public java.lang.String getKey(int index) {
      return key_.get(index);
    }
    /**
     * <code>repeated string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes(int index) {
      return key_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < key_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < key_.size(); i++) {
          dataSize += computeStringSizeNoTag(key_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getKeyList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys)) {
        return super.equals(obj);
      }
      org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys other = (org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys) obj;

      boolean result = true;
      result = result && getKeyList()
          .equals(other.getKeyList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getKeyCount() > 0) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKeyList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Keys}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Keys)
        org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.KeysOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.internal_static_Keys_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.internal_static_Keys_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys.class, org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys.Builder.class);
      }

      // Construct using org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        key_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.internal_static_Keys_descriptor;
      }

      @java.lang.Override
      public org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys getDefaultInstanceForType() {
        return org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys.getDefaultInstance();
      }

      @java.lang.Override
      public org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys build() {
        org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys buildPartial() {
        org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys result = new org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          key_ = key_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.key_ = key_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys) {
          return mergeFrom((org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys other) {
        if (other == org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys.getDefaultInstance()) return this;
        if (!other.key_.isEmpty()) {
          if (key_.isEmpty()) {
            key_ = other.key_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureKeyIsMutable();
            key_.addAll(other.key_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList key_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureKeyIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          key_ = new com.google.protobuf.LazyStringArrayList(key_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string key = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getKeyList() {
        return key_.getUnmodifiableView();
      }
      /**
       * <code>repeated string key = 1;</code>
       */
      public int getKeyCount() {
        return key_.size();
      }
      /**
       * <code>repeated string key = 1;</code>
       */
      public java.lang.String getKey(int index) {
        return key_.get(index);
      }
      /**
       * <code>repeated string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes(int index) {
        return key_.getByteString(index);
      }
      /**
       * <code>repeated string key = 1;</code>
       */
      public Builder setKey(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeyIsMutable();
        key_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string key = 1;</code>
       */
      public Builder addKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeyIsMutable();
        key_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string key = 1;</code>
       */
      public Builder addAllKey(
          java.lang.Iterable<java.lang.String> values) {
        ensureKeyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, key_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string key = 1;</code>
       */
      public Builder clearKey() {
        key_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string key = 1;</code>
       */
      public Builder addKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureKeyIsMutable();
        key_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Keys)
    }

    // @@protoc_insertion_point(class_scope:Keys)
    private static final org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys();
    }

    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Keys>
        PARSER = new com.google.protobuf.AbstractParser<Keys>() {
      @java.lang.Override
      public Keys parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Keys(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Keys> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Keys> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Keys getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 responseCode = 1;</code>
     */
    int getResponseCode();

    /**
     * <code>string responseMessage = 2;</code>
     */
    java.lang.String getResponseMessage();
    /**
     * <code>string responseMessage = 2;</code>
     */
    com.google.protobuf.ByteString
        getResponseMessageBytes();
  }
  /**
   * Protobuf type {@code Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      responseCode_ = 0;
      responseMessage_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              responseCode_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              responseMessage_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message.class, org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message.Builder.class);
    }

    public static final int RESPONSECODE_FIELD_NUMBER = 1;
    private int responseCode_;
    /**
     * <code>int32 responseCode = 1;</code>
     */
    public int getResponseCode() {
      return responseCode_;
    }

    public static final int RESPONSEMESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object responseMessage_;
    /**
     * <code>string responseMessage = 2;</code>
     */
    public java.lang.String getResponseMessage() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string responseMessage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getResponseMessageBytes() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (responseCode_ != 0) {
        output.writeInt32(1, responseCode_);
      }
      if (!getResponseMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, responseMessage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (responseCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, responseCode_);
      }
      if (!getResponseMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, responseMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message)) {
        return super.equals(obj);
      }
      org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message other = (org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message) obj;

      boolean result = true;
      result = result && (getResponseCode()
          == other.getResponseCode());
      result = result && getResponseMessage()
          .equals(other.getResponseMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSECODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseCode();
      hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.internal_static_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message.class, org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message.Builder.class);
      }

      // Construct using org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responseCode_ = 0;

        responseMessage_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.internal_static_Message_descriptor;
      }

      @java.lang.Override
      public org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message getDefaultInstanceForType() {
        return org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message.getDefaultInstance();
      }

      @java.lang.Override
      public org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message build() {
        org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message buildPartial() {
        org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message result = new org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message(this);
        result.responseCode_ = responseCode_;
        result.responseMessage_ = responseMessage_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message) {
          return mergeFrom((org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message other) {
        if (other == org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message.getDefaultInstance()) return this;
        if (other.getResponseCode() != 0) {
          setResponseCode(other.getResponseCode());
        }
        if (!other.getResponseMessage().isEmpty()) {
          responseMessage_ = other.responseMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int responseCode_ ;
      /**
       * <code>int32 responseCode = 1;</code>
       */
      public int getResponseCode() {
        return responseCode_;
      }
      /**
       * <code>int32 responseCode = 1;</code>
       */
      public Builder setResponseCode(int value) {
        
        responseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 responseCode = 1;</code>
       */
      public Builder clearResponseCode() {
        
        responseCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object responseMessage_ = "";
      /**
       * <code>string responseMessage = 2;</code>
       */
      public java.lang.String getResponseMessage() {
        java.lang.Object ref = responseMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string responseMessage = 2;</code>
       */
      public com.google.protobuf.ByteString
          getResponseMessageBytes() {
        java.lang.Object ref = responseMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responseMessage = 2;</code>
       */
      public Builder setResponseMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string responseMessage = 2;</code>
       */
      public Builder clearResponseMessage() {
        
        responseMessage_ = getDefaultInstance().getResponseMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string responseMessage = 2;</code>
       */
      public Builder setResponseMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseMessage_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message();
    }

    public static org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.iu.engrcloudcomputing.mapreduce.mapper.wordcount.autogenerated.Master.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Keys_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Keys_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Master.proto\"\023\n\004Keys\022\013\n\003key\030\001 \003(\t\"8\n\007M" +
      "essage\022\024\n\014responseCode\030\001 \001(\005\022\027\n\017response" +
      "Message\030\002 \001(\t2*\n\tMapperAck\022\035\n\nmappedKeys" +
      "\022\005.Keys\032\010.Message2+\n\nReducerAck\022\035\n\nreduc" +
      "eKeys\022\005.Keys\032\010.MessageBD\nBorg.iu.engrclo" +
      "udcomputing.mapreduce.mapper.wordcount.a" +
      "utogeneratedb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Keys_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Keys_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Keys_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "ResponseCode", "ResponseMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
