package org.iu.engrcloudcomputing.mapreduce.mapred.master.iml;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master;
import org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.ShutDownMasterGrpc;
import org.junit.jupiter.api.Assertions;

public class ShutDownServiceTest {

    public static void main(String[] args) {
        ManagedChannel channel = ManagedChannelBuilder.forAddress("localhost", 9001).usePlaintext().build();
        ShutDownMasterGrpc.ShutDownMasterBlockingStub blockingStub = ShutDownMasterGrpc.newBlockingStub(channel);

        Master.Message message = blockingStub.shutDown(Master.Empty.newBuilder().build());

        Assertions.assertEquals(200, message.getResponseCode());
    }
}
