package org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated;

import static io.grpc.MethodDescriptor.generateFullMethodName;
import static io.grpc.stub.ClientCalls.asyncBidiStreamingCall;
import static io.grpc.stub.ClientCalls.asyncClientStreamingCall;
import static io.grpc.stub.ClientCalls.asyncServerStreamingCall;
import static io.grpc.stub.ClientCalls.asyncUnaryCall;
import static io.grpc.stub.ClientCalls.blockingServerStreamingCall;
import static io.grpc.stub.ClientCalls.blockingUnaryCall;
import static io.grpc.stub.ClientCalls.futureUnaryCall;
import static io.grpc.stub.ServerCalls.asyncBidiStreamingCall;
import static io.grpc.stub.ServerCalls.asyncClientStreamingCall;
import static io.grpc.stub.ServerCalls.asyncServerStreamingCall;
import static io.grpc.stub.ServerCalls.asyncUnaryCall;
import static io.grpc.stub.ServerCalls.asyncUnimplementedStreamingCall;
import static io.grpc.stub.ServerCalls.asyncUnimplementedUnaryCall;

/**
 */
@javax.annotation.Generated(
    value = "by gRPC proto compiler (version 1.15.0)",
    comments = "Source: Master.proto")
public final class ReducerAckGrpc {

  private ReducerAckGrpc() {}

  public static final String SERVICE_NAME = "ReducerAck";

  // Static method descriptors that strictly reflect the proto.
  private static volatile io.grpc.MethodDescriptor<org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Keys,
      org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Message> getReduceKeysMethod;

  @io.grpc.stub.annotations.RpcMethod(
      fullMethodName = SERVICE_NAME + '/' + "reduceKeys",
      requestType = org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Keys.class,
      responseType = org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Message.class,
      methodType = io.grpc.MethodDescriptor.MethodType.UNARY)
  public static io.grpc.MethodDescriptor<org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Keys,
      org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Message> getReduceKeysMethod() {
    io.grpc.MethodDescriptor<org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Keys, org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Message> getReduceKeysMethod;
    if ((getReduceKeysMethod = ReducerAckGrpc.getReduceKeysMethod) == null) {
      synchronized (ReducerAckGrpc.class) {
        if ((getReduceKeysMethod = ReducerAckGrpc.getReduceKeysMethod) == null) {
          ReducerAckGrpc.getReduceKeysMethod = getReduceKeysMethod = 
              io.grpc.MethodDescriptor.<org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Keys, org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Message>newBuilder()
              .setType(io.grpc.MethodDescriptor.MethodType.UNARY)
              .setFullMethodName(generateFullMethodName(
                  "ReducerAck", "reduceKeys"))
              .setSampledToLocalTracing(true)
              .setRequestMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Keys.getDefaultInstance()))
              .setResponseMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Message.getDefaultInstance()))
                  .setSchemaDescriptor(new ReducerAckMethodDescriptorSupplier("reduceKeys"))
                  .build();
          }
        }
     }
     return getReduceKeysMethod;
  }

  /**
   * Creates a new async stub that supports all call types for the service
   */
  public static ReducerAckStub newStub(io.grpc.Channel channel) {
    return new ReducerAckStub(channel);
  }

  /**
   * Creates a new blocking-style stub that supports unary and streaming output calls on the service
   */
  public static ReducerAckBlockingStub newBlockingStub(
      io.grpc.Channel channel) {
    return new ReducerAckBlockingStub(channel);
  }

  /**
   * Creates a new ListenableFuture-style stub that supports unary calls on the service
   */
  public static ReducerAckFutureStub newFutureStub(
      io.grpc.Channel channel) {
    return new ReducerAckFutureStub(channel);
  }

  /**
   */
  public static abstract class ReducerAckImplBase implements io.grpc.BindableService {

    /**
     */
    public void reduceKeys(org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Keys request,
        io.grpc.stub.StreamObserver<org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Message> responseObserver) {
      asyncUnimplementedUnaryCall(getReduceKeysMethod(), responseObserver);
    }

    @java.lang.Override public final io.grpc.ServerServiceDefinition bindService() {
      return io.grpc.ServerServiceDefinition.builder(getServiceDescriptor())
          .addMethod(
            getReduceKeysMethod(),
            asyncUnaryCall(
              new MethodHandlers<
                org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Keys,
                org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Message>(
                  this, METHODID_REDUCE_KEYS)))
          .build();
    }
  }

  /**
   */
  public static final class ReducerAckStub extends io.grpc.stub.AbstractStub<ReducerAckStub> {
    private ReducerAckStub(io.grpc.Channel channel) {
      super(channel);
    }

    private ReducerAckStub(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      super(channel, callOptions);
    }

    @java.lang.Override
    protected ReducerAckStub build(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      return new ReducerAckStub(channel, callOptions);
    }

    /**
     */
    public void reduceKeys(org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Keys request,
        io.grpc.stub.StreamObserver<org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Message> responseObserver) {
      asyncUnaryCall(
          getChannel().newCall(getReduceKeysMethod(), getCallOptions()), request, responseObserver);
    }
  }

  /**
   */
  public static final class ReducerAckBlockingStub extends io.grpc.stub.AbstractStub<ReducerAckBlockingStub> {
    private ReducerAckBlockingStub(io.grpc.Channel channel) {
      super(channel);
    }

    private ReducerAckBlockingStub(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      super(channel, callOptions);
    }

    @java.lang.Override
    protected ReducerAckBlockingStub build(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      return new ReducerAckBlockingStub(channel, callOptions);
    }

    /**
     */
    public org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Message reduceKeys(org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Keys request) {
      return blockingUnaryCall(
          getChannel(), getReduceKeysMethod(), getCallOptions(), request);
    }
  }

  /**
   */
  public static final class ReducerAckFutureStub extends io.grpc.stub.AbstractStub<ReducerAckFutureStub> {
    private ReducerAckFutureStub(io.grpc.Channel channel) {
      super(channel);
    }

    private ReducerAckFutureStub(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      super(channel, callOptions);
    }

    @java.lang.Override
    protected ReducerAckFutureStub build(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      return new ReducerAckFutureStub(channel, callOptions);
    }

    /**
     */
    public com.google.common.util.concurrent.ListenableFuture<org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Message> reduceKeys(
        org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Keys request) {
      return futureUnaryCall(
          getChannel().newCall(getReduceKeysMethod(), getCallOptions()), request);
    }
  }

  private static final int METHODID_REDUCE_KEYS = 0;

  private static final class MethodHandlers<Req, Resp> implements
      io.grpc.stub.ServerCalls.UnaryMethod<Req, Resp>,
      io.grpc.stub.ServerCalls.ServerStreamingMethod<Req, Resp>,
      io.grpc.stub.ServerCalls.ClientStreamingMethod<Req, Resp>,
      io.grpc.stub.ServerCalls.BidiStreamingMethod<Req, Resp> {
    private final ReducerAckImplBase serviceImpl;
    private final int methodId;

    MethodHandlers(ReducerAckImplBase serviceImpl, int methodId) {
      this.serviceImpl = serviceImpl;
      this.methodId = methodId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("unchecked")
    public void invoke(Req request, io.grpc.stub.StreamObserver<Resp> responseObserver) {
      switch (methodId) {
        case METHODID_REDUCE_KEYS:
          serviceImpl.reduceKeys((org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Keys) request,
              (io.grpc.stub.StreamObserver<org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.Message>) responseObserver);
          break;
        default:
          throw new AssertionError();
      }
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("unchecked")
    public io.grpc.stub.StreamObserver<Req> invoke(
        io.grpc.stub.StreamObserver<Resp> responseObserver) {
      switch (methodId) {
        default:
          throw new AssertionError();
      }
    }
  }

  private static abstract class ReducerAckBaseDescriptorSupplier
      implements io.grpc.protobuf.ProtoFileDescriptorSupplier, io.grpc.protobuf.ProtoServiceDescriptorSupplier {
    ReducerAckBaseDescriptorSupplier() {}

    @java.lang.Override
    public com.google.protobuf.Descriptors.FileDescriptor getFileDescriptor() {
      return org.iu.engrcloudcomputing.mapreduce.reducer.autogenerated.Master.getDescriptor();
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.ServiceDescriptor getServiceDescriptor() {
      return getFileDescriptor().findServiceByName("ReducerAck");
    }
  }

  private static final class ReducerAckFileDescriptorSupplier
      extends ReducerAckBaseDescriptorSupplier {
    ReducerAckFileDescriptorSupplier() {}
  }

  private static final class ReducerAckMethodDescriptorSupplier
      extends ReducerAckBaseDescriptorSupplier
      implements io.grpc.protobuf.ProtoMethodDescriptorSupplier {
    private final String methodName;

    ReducerAckMethodDescriptorSupplier(String methodName) {
      this.methodName = methodName;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.MethodDescriptor getMethodDescriptor() {
      return getServiceDescriptor().findMethodByName(methodName);
    }
  }

  private static volatile io.grpc.ServiceDescriptor serviceDescriptor;

  public static io.grpc.ServiceDescriptor getServiceDescriptor() {
    io.grpc.ServiceDescriptor result = serviceDescriptor;
    if (result == null) {
      synchronized (ReducerAckGrpc.class) {
        result = serviceDescriptor;
        if (result == null) {
          serviceDescriptor = result = io.grpc.ServiceDescriptor.newBuilder(SERVICE_NAME)
              .setSchemaDescriptor(new ReducerAckFileDescriptorSupplier())
              .addMethod(getReduceKeysMethod())
              .build();
        }
      }
    }
    return result;
  }
}
