package org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated;

import static io.grpc.MethodDescriptor.generateFullMethodName;
import static io.grpc.stub.ClientCalls.asyncUnaryCall;
import static io.grpc.stub.ClientCalls.blockingUnaryCall;
import static io.grpc.stub.ClientCalls.futureUnaryCall;
import static io.grpc.stub.ServerCalls.asyncUnaryCall;
import static io.grpc.stub.ServerCalls.asyncUnimplementedUnaryCall;

/**
 */
@javax.annotation.Generated(
    value = "by gRPC proto compiler (version 1.15.0)",
    comments = "Source: Master.proto")
public final class ShutDownMasterGrpc {

  private ShutDownMasterGrpc() {}

  public static final String SERVICE_NAME = "ShutDownMaster";

  // Static method descriptors that strictly reflect the proto.
  private static volatile io.grpc.MethodDescriptor<Master.Empty,
      Master.Message> getShutDownMethod;

  @io.grpc.stub.annotations.RpcMethod(
      fullMethodName = SERVICE_NAME + '/' + "shutDown",
      requestType = Master.Empty.class,
      responseType = Master.Message.class,
      methodType = io.grpc.MethodDescriptor.MethodType.UNARY)
  public static io.grpc.MethodDescriptor<Master.Empty,
      Master.Message> getShutDownMethod() {
    io.grpc.MethodDescriptor<Master.Empty, Master.Message> getShutDownMethod;
    if ((getShutDownMethod = ShutDownMasterGrpc.getShutDownMethod) == null) {
      synchronized (ShutDownMasterGrpc.class) {
        if ((getShutDownMethod = ShutDownMasterGrpc.getShutDownMethod) == null) {
          ShutDownMasterGrpc.getShutDownMethod = getShutDownMethod =
              io.grpc.MethodDescriptor.<Master.Empty, Master.Message>newBuilder()
              .setType(io.grpc.MethodDescriptor.MethodType.UNARY)
              .setFullMethodName(generateFullMethodName(
                  "ShutDownMaster", "shutDown"))
              .setSampledToLocalTracing(true)
              .setRequestMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  Master.Empty.getDefaultInstance()))
              .setResponseMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  Master.Message.getDefaultInstance()))
                  .setSchemaDescriptor(new ShutDownMasterMethodDescriptorSupplier("shutDown"))
                  .build();
          }
        }
     }
     return getShutDownMethod;
  }

  /**
   * Creates a new async stub that supports all call types for the service
   */
  public static ShutDownMasterStub newStub(io.grpc.Channel channel) {
    return new ShutDownMasterStub(channel);
  }

  /**
   * Creates a new blocking-style stub that supports unary and streaming output calls on the service
   */
  public static ShutDownMasterBlockingStub newBlockingStub(
      io.grpc.Channel channel) {
    return new ShutDownMasterBlockingStub(channel);
  }

  /**
   * Creates a new ListenableFuture-style stub that supports unary calls on the service
   */
  public static ShutDownMasterFutureStub newFutureStub(
      io.grpc.Channel channel) {
    return new ShutDownMasterFutureStub(channel);
  }

  /**
   */
  public static abstract class ShutDownMasterImplBase implements io.grpc.BindableService {

    /**
     */
    public void shutDown(Master.Empty request,
                         io.grpc.stub.StreamObserver<Master.Message> responseObserver) {
      asyncUnimplementedUnaryCall(getShutDownMethod(), responseObserver);
    }

    @Override public final io.grpc.ServerServiceDefinition bindService() {
      return io.grpc.ServerServiceDefinition.builder(getServiceDescriptor())
          .addMethod(
            getShutDownMethod(),
            asyncUnaryCall(
              new MethodHandlers<
                Master.Empty,
                Master.Message>(
                  this, METHODID_SHUT_DOWN)))
          .build();
    }
  }

  /**
   */
  public static final class ShutDownMasterStub extends io.grpc.stub.AbstractStub<ShutDownMasterStub> {
    private ShutDownMasterStub(io.grpc.Channel channel) {
      super(channel);
    }

    private ShutDownMasterStub(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      super(channel, callOptions);
    }

    @Override
    protected ShutDownMasterStub build(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      return new ShutDownMasterStub(channel, callOptions);
    }

    /**
     */
    public void shutDown(Master.Empty request,
                         io.grpc.stub.StreamObserver<Master.Message> responseObserver) {
      asyncUnaryCall(
          getChannel().newCall(getShutDownMethod(), getCallOptions()), request, responseObserver);
    }
  }

  /**
   */
  public static final class ShutDownMasterBlockingStub extends io.grpc.stub.AbstractStub<ShutDownMasterBlockingStub> {
    private ShutDownMasterBlockingStub(io.grpc.Channel channel) {
      super(channel);
    }

    private ShutDownMasterBlockingStub(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      super(channel, callOptions);
    }

    @Override
    protected ShutDownMasterBlockingStub build(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      return new ShutDownMasterBlockingStub(channel, callOptions);
    }

    /**
     */
    public Master.Message shutDown(Master.Empty request) {
      return blockingUnaryCall(
          getChannel(), getShutDownMethod(), getCallOptions(), request);
    }
  }

  /**
   */
  public static final class ShutDownMasterFutureStub extends io.grpc.stub.AbstractStub<ShutDownMasterFutureStub> {
    private ShutDownMasterFutureStub(io.grpc.Channel channel) {
      super(channel);
    }

    private ShutDownMasterFutureStub(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      super(channel, callOptions);
    }

    @Override
    protected ShutDownMasterFutureStub build(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      return new ShutDownMasterFutureStub(channel, callOptions);
    }

    /**
     */
    public com.google.common.util.concurrent.ListenableFuture<Master.Message> shutDown(
        Master.Empty request) {
      return futureUnaryCall(
          getChannel().newCall(getShutDownMethod(), getCallOptions()), request);
    }
  }

  private static final int METHODID_SHUT_DOWN = 0;

  private static final class MethodHandlers<Req, Resp> implements
      io.grpc.stub.ServerCalls.UnaryMethod<Req, Resp>,
      io.grpc.stub.ServerCalls.ServerStreamingMethod<Req, Resp>,
      io.grpc.stub.ServerCalls.ClientStreamingMethod<Req, Resp>,
      io.grpc.stub.ServerCalls.BidiStreamingMethod<Req, Resp> {
    private final ShutDownMasterImplBase serviceImpl;
    private final int methodId;

    MethodHandlers(ShutDownMasterImplBase serviceImpl, int methodId) {
      this.serviceImpl = serviceImpl;
      this.methodId = methodId;
    }

    @Override
    @SuppressWarnings("unchecked")
    public void invoke(Req request, io.grpc.stub.StreamObserver<Resp> responseObserver) {
      switch (methodId) {
        case METHODID_SHUT_DOWN:
          serviceImpl.shutDown((Master.Empty) request,
              (io.grpc.stub.StreamObserver<Master.Message>) responseObserver);
          break;
        default:
          throw new AssertionError();
      }
    }

    @Override
    @SuppressWarnings("unchecked")
    public io.grpc.stub.StreamObserver<Req> invoke(
        io.grpc.stub.StreamObserver<Resp> responseObserver) {
      switch (methodId) {
        default:
          throw new AssertionError();
      }
    }
  }

  private static abstract class ShutDownMasterBaseDescriptorSupplier
      implements io.grpc.protobuf.ProtoFileDescriptorSupplier, io.grpc.protobuf.ProtoServiceDescriptorSupplier {
    ShutDownMasterBaseDescriptorSupplier() {}

    @Override
    public com.google.protobuf.Descriptors.FileDescriptor getFileDescriptor() {
      return Master.getDescriptor();
    }

    @Override
    public com.google.protobuf.Descriptors.ServiceDescriptor getServiceDescriptor() {
      return getFileDescriptor().findServiceByName("ShutDownMaster");
    }
  }

  private static final class ShutDownMasterFileDescriptorSupplier
      extends ShutDownMasterBaseDescriptorSupplier {
    ShutDownMasterFileDescriptorSupplier() {}
  }

  private static final class ShutDownMasterMethodDescriptorSupplier
      extends ShutDownMasterBaseDescriptorSupplier
      implements io.grpc.protobuf.ProtoMethodDescriptorSupplier {
    private final String methodName;

    ShutDownMasterMethodDescriptorSupplier(String methodName) {
      this.methodName = methodName;
    }

    @Override
    public com.google.protobuf.Descriptors.MethodDescriptor getMethodDescriptor() {
      return getServiceDescriptor().findMethodByName(methodName);
    }
  }

  private static volatile io.grpc.ServiceDescriptor serviceDescriptor;

  public static io.grpc.ServiceDescriptor getServiceDescriptor() {
    io.grpc.ServiceDescriptor result = serviceDescriptor;
    if (result == null) {
      synchronized (ShutDownMasterGrpc.class) {
        result = serviceDescriptor;
        if (result == null) {
          serviceDescriptor = result = io.grpc.ServiceDescriptor.newBuilder(SERVICE_NAME)
              .setSchemaDescriptor(new ShutDownMasterFileDescriptorSupplier())
              .addMethod(getShutDownMethod())
              .build();
        }
      }
    }
    return result;
  }
}
