package org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated;

import static io.grpc.MethodDescriptor.generateFullMethodName;
import static io.grpc.stub.ClientCalls.asyncBidiStreamingCall;
import static io.grpc.stub.ClientCalls.asyncClientStreamingCall;
import static io.grpc.stub.ClientCalls.asyncServerStreamingCall;
import static io.grpc.stub.ClientCalls.asyncUnaryCall;
import static io.grpc.stub.ClientCalls.blockingServerStreamingCall;
import static io.grpc.stub.ClientCalls.blockingUnaryCall;
import static io.grpc.stub.ClientCalls.futureUnaryCall;
import static io.grpc.stub.ServerCalls.asyncBidiStreamingCall;
import static io.grpc.stub.ServerCalls.asyncClientStreamingCall;
import static io.grpc.stub.ServerCalls.asyncServerStreamingCall;
import static io.grpc.stub.ServerCalls.asyncUnaryCall;
import static io.grpc.stub.ServerCalls.asyncUnimplementedStreamingCall;
import static io.grpc.stub.ServerCalls.asyncUnimplementedUnaryCall;

/**
 */
@javax.annotation.Generated(
    value = "by gRPC proto compiler (version 1.15.0)",
    comments = "Source: Master.proto")
public final class BeginMapReduceGrpc {

  private BeginMapReduceGrpc() {}

  public static final String SERVICE_NAME = "BeginMapReduce";

  // Static method descriptors that strictly reflect the proto.
  private static volatile io.grpc.MethodDescriptor<org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceParams,
      org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceResponse> getMapReduceMethod;

  @io.grpc.stub.annotations.RpcMethod(
      fullMethodName = SERVICE_NAME + '/' + "mapReduce",
      requestType = org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceParams.class,
      responseType = org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceResponse.class,
      methodType = io.grpc.MethodDescriptor.MethodType.UNARY)
  public static io.grpc.MethodDescriptor<org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceParams,
      org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceResponse> getMapReduceMethod() {
    io.grpc.MethodDescriptor<org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceParams, org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceResponse> getMapReduceMethod;
    if ((getMapReduceMethod = BeginMapReduceGrpc.getMapReduceMethod) == null) {
      synchronized (BeginMapReduceGrpc.class) {
        if ((getMapReduceMethod = BeginMapReduceGrpc.getMapReduceMethod) == null) {
          BeginMapReduceGrpc.getMapReduceMethod = getMapReduceMethod = 
              io.grpc.MethodDescriptor.<org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceParams, org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceResponse>newBuilder()
              .setType(io.grpc.MethodDescriptor.MethodType.UNARY)
              .setFullMethodName(generateFullMethodName(
                  "BeginMapReduce", "mapReduce"))
              .setSampledToLocalTracing(true)
              .setRequestMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceParams.getDefaultInstance()))
              .setResponseMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceResponse.getDefaultInstance()))
                  .setSchemaDescriptor(new BeginMapReduceMethodDescriptorSupplier("mapReduce"))
                  .build();
          }
        }
     }
     return getMapReduceMethod;
  }

  /**
   * Creates a new async stub that supports all call types for the service
   */
  public static BeginMapReduceStub newStub(io.grpc.Channel channel) {
    return new BeginMapReduceStub(channel);
  }

  /**
   * Creates a new blocking-style stub that supports unary and streaming output calls on the service
   */
  public static BeginMapReduceBlockingStub newBlockingStub(
      io.grpc.Channel channel) {
    return new BeginMapReduceBlockingStub(channel);
  }

  /**
   * Creates a new ListenableFuture-style stub that supports unary calls on the service
   */
  public static BeginMapReduceFutureStub newFutureStub(
      io.grpc.Channel channel) {
    return new BeginMapReduceFutureStub(channel);
  }

  /**
   */
  public static abstract class BeginMapReduceImplBase implements io.grpc.BindableService {

    /**
     */
    public void mapReduce(org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceParams request,
        io.grpc.stub.StreamObserver<org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceResponse> responseObserver) {
      asyncUnimplementedUnaryCall(getMapReduceMethod(), responseObserver);
    }

    @java.lang.Override public final io.grpc.ServerServiceDefinition bindService() {
      return io.grpc.ServerServiceDefinition.builder(getServiceDescriptor())
          .addMethod(
            getMapReduceMethod(),
            asyncUnaryCall(
              new MethodHandlers<
                org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceParams,
                org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceResponse>(
                  this, METHODID_MAP_REDUCE)))
          .build();
    }
  }

  /**
   */
  public static final class BeginMapReduceStub extends io.grpc.stub.AbstractStub<BeginMapReduceStub> {
    private BeginMapReduceStub(io.grpc.Channel channel) {
      super(channel);
    }

    private BeginMapReduceStub(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      super(channel, callOptions);
    }

    @java.lang.Override
    protected BeginMapReduceStub build(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      return new BeginMapReduceStub(channel, callOptions);
    }

    /**
     */
    public void mapReduce(org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceParams request,
        io.grpc.stub.StreamObserver<org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceResponse> responseObserver) {
      asyncUnaryCall(
          getChannel().newCall(getMapReduceMethod(), getCallOptions()), request, responseObserver);
    }
  }

  /**
   */
  public static final class BeginMapReduceBlockingStub extends io.grpc.stub.AbstractStub<BeginMapReduceBlockingStub> {
    private BeginMapReduceBlockingStub(io.grpc.Channel channel) {
      super(channel);
    }

    private BeginMapReduceBlockingStub(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      super(channel, callOptions);
    }

    @java.lang.Override
    protected BeginMapReduceBlockingStub build(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      return new BeginMapReduceBlockingStub(channel, callOptions);
    }

    /**
     */
    public org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceResponse mapReduce(org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceParams request) {
      return blockingUnaryCall(
          getChannel(), getMapReduceMethod(), getCallOptions(), request);
    }
  }

  /**
   */
  public static final class BeginMapReduceFutureStub extends io.grpc.stub.AbstractStub<BeginMapReduceFutureStub> {
    private BeginMapReduceFutureStub(io.grpc.Channel channel) {
      super(channel);
    }

    private BeginMapReduceFutureStub(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      super(channel, callOptions);
    }

    @java.lang.Override
    protected BeginMapReduceFutureStub build(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      return new BeginMapReduceFutureStub(channel, callOptions);
    }

    /**
     */
    public com.google.common.util.concurrent.ListenableFuture<org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceResponse> mapReduce(
        org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceParams request) {
      return futureUnaryCall(
          getChannel().newCall(getMapReduceMethod(), getCallOptions()), request);
    }
  }

  private static final int METHODID_MAP_REDUCE = 0;

  private static final class MethodHandlers<Req, Resp> implements
      io.grpc.stub.ServerCalls.UnaryMethod<Req, Resp>,
      io.grpc.stub.ServerCalls.ServerStreamingMethod<Req, Resp>,
      io.grpc.stub.ServerCalls.ClientStreamingMethod<Req, Resp>,
      io.grpc.stub.ServerCalls.BidiStreamingMethod<Req, Resp> {
    private final BeginMapReduceImplBase serviceImpl;
    private final int methodId;

    MethodHandlers(BeginMapReduceImplBase serviceImpl, int methodId) {
      this.serviceImpl = serviceImpl;
      this.methodId = methodId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("unchecked")
    public void invoke(Req request, io.grpc.stub.StreamObserver<Resp> responseObserver) {
      switch (methodId) {
        case METHODID_MAP_REDUCE:
          serviceImpl.mapReduce((org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceParams) request,
              (io.grpc.stub.StreamObserver<org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.MapReduceResponse>) responseObserver);
          break;
        default:
          throw new AssertionError();
      }
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("unchecked")
    public io.grpc.stub.StreamObserver<Req> invoke(
        io.grpc.stub.StreamObserver<Resp> responseObserver) {
      switch (methodId) {
        default:
          throw new AssertionError();
      }
    }
  }

  private static abstract class BeginMapReduceBaseDescriptorSupplier
      implements io.grpc.protobuf.ProtoFileDescriptorSupplier, io.grpc.protobuf.ProtoServiceDescriptorSupplier {
    BeginMapReduceBaseDescriptorSupplier() {}

    @java.lang.Override
    public com.google.protobuf.Descriptors.FileDescriptor getFileDescriptor() {
      return org.iu.engrcloudcomputing.mapreduce.mapred.autogenerated.Master.getDescriptor();
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.ServiceDescriptor getServiceDescriptor() {
      return getFileDescriptor().findServiceByName("BeginMapReduce");
    }
  }

  private static final class BeginMapReduceFileDescriptorSupplier
      extends BeginMapReduceBaseDescriptorSupplier {
    BeginMapReduceFileDescriptorSupplier() {}
  }

  private static final class BeginMapReduceMethodDescriptorSupplier
      extends BeginMapReduceBaseDescriptorSupplier
      implements io.grpc.protobuf.ProtoMethodDescriptorSupplier {
    private final String methodName;

    BeginMapReduceMethodDescriptorSupplier(String methodName) {
      this.methodName = methodName;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.MethodDescriptor getMethodDescriptor() {
      return getServiceDescriptor().findMethodByName(methodName);
    }
  }

  private static volatile io.grpc.ServiceDescriptor serviceDescriptor;

  public static io.grpc.ServiceDescriptor getServiceDescriptor() {
    io.grpc.ServiceDescriptor result = serviceDescriptor;
    if (result == null) {
      synchronized (BeginMapReduceGrpc.class) {
        result = serviceDescriptor;
        if (result == null) {
          serviceDescriptor = result = io.grpc.ServiceDescriptor.newBuilder(SERVICE_NAME)
              .setSchemaDescriptor(new BeginMapReduceFileDescriptorSupplier())
              .addMethod(getMapReduceMethod())
              .build();
        }
      }
    }
    return result;
  }
}
